CREATE FUNCTION test_function() RETURNS TEXT
  AS 'MODULE_PATHNAME'
  LANGUAGE C STRICT IMMUTABLE;

CREATE FUNCTION call_python_udf_from_c() RETURNS TEXT
  AS 'MODULE_PATHNAME'
  LANGUAGE C STRICT IMMUTABLE;